#!/usr/bin/env node

/**
 * Developer Notification System for CI/CD Pipeline
 * Sends alerts for test failures with process-specific debugging information
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

class NotificationSystem {
  constructor(options = {}) {
    this.config = {
      github: {
        enabled: options.githubEnabled !== false,
        token: process.env.GITHUB_TOKEN,
        owner: process.env.GITHUB_REPOSITORY_OWNER,
        repo: process.env.GITHUB_REPOSITORY?.split("/")[1],
        apiUrl: "https://api.github.com",
      },
      notifications: {
        createIssues: options.createIssues !== false,
        commentOnPR: options.commentOnPR !== false,
        sendWebhooks: options.sendWebhooks || false,
        webhookUrl: process.env.WEBHOOK_URL,
      },
      thresholds: {
        criticalFailureThreshold: options.criticalFailureThreshold || 5,
        persistentFailureThreshold: options.persistentFailureThreshold || 3,
        ...options.thresholds,
      },
      templates: this.loadNotificationTemplates(),
      ...options,
    };

    this.logger = this.createLogger();
    this.githubApi = this.initializeGitHubAPI();
  }

  createLogger() {
    return {
      info: (msg, ...args) => console.log(`[NOTIFICATION] ${new Date().toISOString()} ${msg}`, ...args),
      warn: (msg, ...args) => console.warn(`[NOTIFICATION] ${new Date().toISOString()} ${msg}`, ...args),
      error: (msg, ...args) => console.error(`[NOTIFICATION] ${new Date().toISOString()} ${msg}`, ...args),
      debug: (msg, ...args) => process.env.DEBUG && console.log(`[DEBUG] ${new Date().toISOString()} ${msg}`, ...args),
    };
  }

  loadNotificationTemplates() {
    return {
      testFailure: {
        subject: "🚨 Test Failure Alert: {process} in {framework}",
        body: `## Test Failure Alert

**Process:** {process}
**Framework:** {framework}
**Branch:** {branch}
**Commit:** {commit}

### Failure Details
{failureDetails}

### Debugging Information
{debuggingInfo}

### Recommended Actions
{recommendedActions}

### Related Artifacts
{artifacts}

---
*Generated by PokéRogue CI/CD Pipeline*`,
      },
      persistentFailure: {
        subject: "⚠️ Persistent Test Failure: {process}",
        body: `## Persistent Test Failure

**Process:** {process}
**Failure Count:** {failureCount}
**First Failed:** {firstFailure}
**Last Failed:** {lastFailure}

### Failure Pattern
{failurePattern}

### Impact Assessment
{impactAssessment}

### Escalation Required
This issue requires immediate attention as it has failed {failureCount} consecutive times.

---
*Generated by PokéRogue CI/CD Pipeline*`,
      },
      qualityGateFailure: {
        subject: "🔒 Quality Gate Failure: Deployment Blocked",
        body: `## Quality Gate Failure

**Status:** FAILED
**Branch:** {branch}
**Commit:** {commit}

### Failed Gates
{failedGates}

### Blocking Issues
{blockingIssues}

### Resolution Steps
{resolutionSteps}

---
*Generated by PokéRogue CI/CD Pipeline*`,
      },
      performanceRegression: {
        subject: "📉 Performance Regression Detected",
        body: `## Performance Regression Alert

**Process:** {process}
**Regression:** {regressionPercentage}%
**Baseline:** {baseline}
**Current:** {current}

### Performance Impact
{performanceImpact}

### Analysis
{performanceAnalysis}

### Optimization Recommendations
{optimizationRecommendations}

---
*Generated by PokéRogue CI/CD Pipeline*`,
      },
    };
  }

  initializeGitHubAPI() {
    if (!this.config.github.enabled || !this.config.github.token) {
      this.logger.warn("GitHub API not configured - GitHub notifications disabled");
      return null;
    }

    return {
      headers: {
        Authorization: `token ${this.config.github.token}`,
        Accept: "application/vnd.github.v3+json",
        "User-Agent": "pokerogue-ci-notification-system",
      },
    };
  }

  async processTestResults(testResults) {
    this.logger.info("📧 Processing test results for notifications");

    try {
      const notifications = [];

      // Analyze test results for different types of failures
      const failures = await this.analyzeFailures(testResults);

      // Process each type of failure
      for (const failure of failures) {
        const notification = await this.createNotification(failure);
        if (notification) {
          notifications.push(notification);
        }
      }

      // Send notifications
      for (const notification of notifications) {
        await this.sendNotification(notification);
      }

      // Update failure tracking
      await this.updateFailureTracking(failures);

      this.logger.info(`✅ Processed ${notifications.length} notifications`);

      return notifications;
    } catch (error) {
      this.logger.error("❌ Failed to process test results for notifications:", error.message);
      throw error;
    }
  }

  async analyzeFailures(testResults) {
    const failures = [];

    // Process framework failures
    for (const [frameworkName, framework] of Object.entries(testResults.frameworks || {})) {
      if (framework.failedTests > 0) {
        // Process each failed test/process
        for (const result of framework.results || []) {
          if (result.success === false) {
            failures.push({
              type: "test-failure",
              framework: frameworkName,
              process: this.extractProcessName(result),
              details: result,
              severity: this.calculateSeverity(result),
              debuggingInfo: await this.generateDebuggingInfo(result),
              artifacts: await this.collectFailureArtifacts(result),
            });
          }
        }
      }
    }

    // Process quality gate failures
    if (testResults.qualityGates && testResults.qualityGates.overallStatus === "fail") {
      failures.push({
        type: "quality-gate-failure",
        gates: testResults.qualityGates.gates.filter(g => !g.passed),
        severity: "critical",
        details: testResults.qualityGates,
      });
    }

    // Process performance regressions
    if (testResults.frameworks.performance) {
      const perfResults = testResults.frameworks.performance.results || [];
      for (const result of perfResults) {
        if (result.regression && result.regression.detected) {
          failures.push({
            type: "performance-regression",
            process: this.extractProcessName(result),
            regression: result.regression,
            severity: "medium",
            details: result,
          });
        }
      }
    }

    // Check for persistent failures
    const persistentFailures = await this.checkPersistentFailures(failures);
    failures.push(...persistentFailures);

    return failures;
  }

  extractProcessName(result) {
    return result.process || result.testName || result.id || "unknown";
  }

  calculateSeverity(result) {
    // Determine severity based on failure characteristics
    if (result.critical || result.framework === "integration") {
      return "critical";
    }
    if (result.framework === "parity" || result.framework === "aos-local") {
      return "high";
    }
    return "medium";
  }

  async generateDebuggingInfo(result) {
    const debugInfo = {
      framework: result.framework,
      timestamp: result.timestamp || new Date().toISOString(),
      errorOutput: result.stderr || result.error || "No error output available",
      exitCode: result.exitCode,
      duration: result.duration,
      environment: {
        node: process.version,
        platform: process.platform,
        memory: process.memoryUsage(),
      },
    };

    // Add framework-specific debugging info
    switch (result.framework) {
      case "aolite":
        debugInfo.aoliteSpecific = {
          luaVersion: "5.3",
          aoliteMode: "test",
          processType: result.type,
        };
        break;
      case "aos-local":
        debugInfo.aosLocalSpecific = {
          deploymentStatus: result.deployment?.status,
          messageFlow: result.messageFlow,
          processTimeout: "5000ms",
        };
        break;
      case "integration":
        debugInfo.integrationSpecific = {
          scenario: result.scenario,
          workflow: result.workflow,
          coordination: result.coordination,
        };
        break;
      case "parity":
        debugInfo.paritySpecific = {
          deviations: result.deviations,
          parityRate: result.parityRate,
          categories: result.categories,
        };
        break;
    }

    // Add process-specific debugging hints
    debugInfo.debuggingHints = this.generateDebuggingHints(result);

    return debugInfo;
  }

  generateDebuggingHints(result) {
    const hints = [];

    // Common debugging hints
    hints.push("Check the test logs for detailed error messages");
    hints.push("Verify that all dependencies are properly installed");

    // Framework-specific hints
    switch (result.framework) {
      case "aolite":
        hints.push("Ensure AO globals are properly mocked in the test environment");
        hints.push("Check for Lua syntax errors in the process file");
        hints.push("Verify that embedded data is properly formatted");
        break;
      case "aos-local":
        hints.push("Check AO process deployment logs");
        hints.push("Verify message passing between processes");
        hints.push("Ensure process size limits are not exceeded");
        break;
      case "integration":
        hints.push("Verify that all required processes are deployed");
        hints.push("Check coordinator process logs for workflow issues");
        hints.push("Ensure state consistency across process boundaries");
        break;
      case "parity":
        hints.push("Compare AO Lua output with TypeScript reference");
        hints.push("Check for floating-point precision differences");
        hints.push("Verify that random seed handling is identical");
        break;
    }

    // Error-specific hints
    if (result.stderr || result.error) {
      const errorText = (result.stderr || result.error).toLowerCase();

      if (errorText.includes("timeout")) {
        hints.push("Consider increasing timeout limits for complex operations");
      }
      if (errorText.includes("memory")) {
        hints.push("Check for memory leaks or excessive memory usage");
      }
      if (errorText.includes("syntax")) {
        hints.push("Review Lua syntax - check for missing end statements or brackets");
      }
      if (errorText.includes("require")) {
        hints.push("Remove require() statements - all dependencies must be embedded");
      }
    }

    return hints;
  }

  async collectFailureArtifacts(result) {
    const artifacts = [];

    // Collect log files
    const logDirs = ["testing/reports", "testing/aolite", "testing/aos-local", "testing/integration"];

    for (const dir of logDirs) {
      const fullPath = path.join(process.cwd(), dir);
      if (fs.existsSync(fullPath)) {
        try {
          const files = fs.readdirSync(fullPath);
          for (const file of files) {
            if (file.includes(result.process) || file.includes(result.framework)) {
              artifacts.push({
                path: path.join(dir, file),
                type: "log",
                size: fs.statSync(path.join(fullPath, file)).size,
              });
            }
          }
        } catch (error) {
          // Ignore errors when collecting artifacts
        }
      }
    }

    return artifacts;
  }

  async checkPersistentFailures(currentFailures) {
    const persistentFailures = [];
    const failureHistoryPath = path.join(process.cwd(), "testing/reports/failure-history.json");

    let failureHistory = {};
    if (fs.existsSync(failureHistoryPath)) {
      try {
        failureHistory = JSON.parse(fs.readFileSync(failureHistoryPath, "utf8"));
      } catch (error) {
        this.logger.warn("Failed to load failure history:", error.message);
      }
    }

    // Track current failures
    for (const failure of currentFailures) {
      const key = `${failure.framework}-${failure.process}`;

      if (!failureHistory[key]) {
        failureHistory[key] = {
          count: 0,
          firstFailure: null,
          lastFailure: null,
          pattern: [],
        };
      }

      failureHistory[key].count++;
      failureHistory[key].lastFailure = new Date().toISOString();
      if (!failureHistory[key].firstFailure) {
        failureHistory[key].firstFailure = failureHistory[key].lastFailure;
      }
      failureHistory[key].pattern.push({
        timestamp: failureHistory[key].lastFailure,
        error: failure.details.error || failure.details.stderr,
      });

      // Check if this qualifies as persistent failure
      if (failureHistory[key].count >= this.config.thresholds.persistentFailureThreshold) {
        persistentFailures.push({
          type: "persistent-failure",
          framework: failure.framework,
          process: failure.process,
          failureCount: failureHistory[key].count,
          firstFailure: failureHistory[key].firstFailure,
          lastFailure: failureHistory[key].lastFailure,
          pattern: failureHistory[key].pattern,
          severity: "critical",
        });
      }
    }

    // Save updated failure history
    try {
      fs.writeFileSync(failureHistoryPath, JSON.stringify(failureHistory, null, 2));
    } catch (error) {
      this.logger.warn("Failed to save failure history:", error.message);
    }

    return persistentFailures;
  }

  async createNotification(failure) {
    let template;
    let data = {
      process: failure.process || "unknown",
      framework: failure.framework || "unknown",
      branch: process.env.GITHUB_REF_NAME || "unknown",
      commit: (process.env.GITHUB_SHA || "unknown").substr(0, 7),
      timestamp: new Date().toISOString(),
    };

    switch (failure.type) {
      case "test-failure":
        template = this.config.templates.testFailure;
        data = {
          ...data,
          failureDetails: this.formatFailureDetails(failure.details),
          debuggingInfo: this.formatDebuggingInfo(failure.debuggingInfo),
          recommendedActions: this.formatRecommendedActions(failure),
          artifacts: this.formatArtifacts(failure.artifacts),
        };
        break;

      case "persistent-failure":
        template = this.config.templates.persistentFailure;
        data = {
          ...data,
          failureCount: failure.failureCount,
          firstFailure: failure.firstFailure,
          lastFailure: failure.lastFailure,
          failurePattern: this.formatFailurePattern(failure.pattern),
          impactAssessment: this.formatImpactAssessment(failure),
        };
        break;

      case "quality-gate-failure":
        template = this.config.templates.qualityGateFailure;
        data = {
          ...data,
          failedGates: this.formatFailedGates(failure.gates),
          blockingIssues: this.formatBlockingIssues(failure.details),
          resolutionSteps: this.formatResolutionSteps(failure.gates),
        };
        break;

      case "performance-regression":
        template = this.config.templates.performanceRegression;
        data = {
          ...data,
          regressionPercentage: failure.regression.percentage.toFixed(1),
          baseline: failure.regression.baseline,
          current: failure.regression.current,
          performanceImpact: this.formatPerformanceImpact(failure.regression),
          performanceAnalysis: this.formatPerformanceAnalysis(failure.details),
          optimizationRecommendations: this.formatOptimizationRecommendations(failure),
        };
        break;

      default:
        this.logger.warn(`Unknown failure type: ${failure.type}`);
        return null;
    }

    return {
      type: failure.type,
      severity: failure.severity,
      subject: this.interpolateTemplate(template.subject, data),
      body: this.interpolateTemplate(template.body, data),
      data,
      failure,
    };
  }

  interpolateTemplate(template, data) {
    return template.replace(/{(\w+)}/g, (match, key) => data[key] || match);
  }

  formatFailureDetails(details) {
    const lines = [
      `**Exit Code:** ${details.exitCode || "N/A"}`,
      `**Duration:** ${details.duration ? (details.duration / 1000).toFixed(1) + "s" : "N/A"}`,
      "**Error Output:**",
    ];

    if (details.stderr || details.error) {
      lines.push("```");
      lines.push(details.stderr || details.error);
      lines.push("```");
    } else {
      lines.push("No error output available");
    }

    return lines.join("\n");
  }

  formatDebuggingInfo(debugInfo) {
    const lines = [
      `**Environment:** Node ${debugInfo.environment.node} on ${debugInfo.environment.platform}`,
      `**Memory Usage:** ${(debugInfo.environment.memory.heapUsed / 1024 / 1024).toFixed(1)} MB`,
      "",
      "**Debugging Hints:**",
    ];

    for (const hint of debugInfo.debuggingHints || []) {
      lines.push(`- ${hint}`);
    }

    return lines.join("\n");
  }

  formatRecommendedActions(failure) {
    const actions = [
      "1. Review the error output and debugging information above",
      "2. Check the specific test file and process implementation",
      "3. Run the test locally to reproduce the issue",
    ];

    switch (failure.severity) {
      case "critical":
        actions.unshift("⚠️ **CRITICAL**: This failure blocks deployment");
        actions.push("4. Create a hotfix if this affects production functionality");
        break;
      case "high":
        actions.push("4. Fix within the current sprint cycle");
        break;
      case "medium":
        actions.push("4. Schedule fix for next development cycle");
        break;
    }

    return actions.join("\n");
  }

  formatArtifacts(artifacts) {
    if (!artifacts || artifacts.length === 0) {
      return "No artifacts available";
    }

    const lines = ["**Available Artifacts:**"];
    for (const artifact of artifacts) {
      lines.push(`- [${artifact.path}](${artifact.path}) (${(artifact.size / 1024).toFixed(1)} KB)`);
    }

    return lines.join("\n");
  }

  formatFailurePattern(pattern) {
    const lines = ["**Recent Failures:**"];
    for (const entry of pattern.slice(-5)) {
      // Last 5 failures
      lines.push(`- ${entry.timestamp}: ${entry.error?.substring(0, 100) || "No error message"}...`);
    }
    return lines.join("\n");
  }

  formatImpactAssessment(failure) {
    return [
      `**Affected Process:** ${failure.process}`,
      `**Affected Framework:** ${failure.framework}`,
      `**Failure Frequency:** ${failure.failureCount} times`,
      `**Impact:** ${failure.severity === "critical" ? "Blocks deployment" : "Reduces confidence in testing"}`,
    ].join("\n");
  }

  formatFailedGates(gates) {
    const lines = [];
    for (const gate of gates) {
      lines.push(`- **${gate.name}:** ${gate.message}`);
    }
    return lines.join("\n");
  }

  formatBlockingIssues(details) {
    const issues = [];

    if (details.violations) {
      for (const violation of details.violations) {
        issues.push(`- ${violation.gate}: ${violation.message}`);
      }
    }

    return issues.length > 0 ? issues.join("\n") : "No specific blocking issues identified";
  }

  formatResolutionSteps(gates) {
    const steps = ["To resolve quality gate failures:"];

    for (const gate of gates) {
      steps.push(`- **${gate.name}:** ${gate.recommendation || "Review gate requirements"}`);
    }

    return steps.join("\n");
  }

  formatPerformanceImpact(regression) {
    return [
      `**Performance degraded by ${regression.percentage.toFixed(1)}%**`,
      `**Baseline:** ${regression.baseline}ms`,
      `**Current:** ${regression.current}ms`,
      `**Difference:** +${(regression.current - regression.baseline).toFixed(1)}ms`,
    ].join("\n");
  }

  formatPerformanceAnalysis(details) {
    return "Performance regression detected. Review recent changes for optimization opportunities.";
  }

  formatOptimizationRecommendations(failure) {
    return [
      "1. Profile the affected process to identify bottlenecks",
      "2. Review recent code changes for performance impact",
      "3. Consider algorithmic improvements or caching strategies",
      "4. Validate against TypeScript baseline performance",
    ].join("\n");
  }

  async sendNotification(notification) {
    const results = [];

    // Send GitHub notifications
    if (this.config.github.enabled && this.githubApi) {
      if (this.config.notifications.createIssues) {
        const issueResult = await this.createGitHubIssue(notification);
        results.push(issueResult);
      }

      if (this.config.notifications.commentOnPR && process.env.GITHUB_EVENT_NAME === "pull_request") {
        const commentResult = await this.createPRComment(notification);
        results.push(commentResult);
      }
    }

    // Send webhook notifications
    if (this.config.notifications.sendWebhooks && this.config.notifications.webhookUrl) {
      const webhookResult = await this.sendWebhook(notification);
      results.push(webhookResult);
    }

    // Log notification (always)
    this.logger.info(`📧 Notification sent: ${notification.subject}`);

    return results;
  }

  async createGitHubIssue(notification) {
    try {
      const issueData = {
        title: notification.subject,
        body: notification.body,
        labels: this.getIssueLabels(notification),
      };

      const response = await this.makeGitHubRequest("POST", "/repos/{owner}/{repo}/issues", issueData);

      this.logger.info(`✅ GitHub issue created: ${response.html_url}`);

      return {
        type: "github-issue",
        success: true,
        url: response.html_url,
        number: response.number,
      };
    } catch (error) {
      this.logger.error("Failed to create GitHub issue:", error.message);
      return {
        type: "github-issue",
        success: false,
        error: error.message,
      };
    }
  }

  async createPRComment(notification) {
    try {
      const commentData = {
        body: `## ${notification.subject}\n\n${notification.body}`,
      };

      const prNumber = process.env.GITHUB_PR_NUMBER || process.env.GITHUB_REF?.match(/\/(\d+)\/merge$/)?.[1];

      if (!prNumber) {
        throw new Error("PR number not found");
      }

      const response = await this.makeGitHubRequest(
        "POST",
        `/repos/{owner}/{repo}/issues/${prNumber}/comments`,
        commentData,
      );

      this.logger.info(`✅ PR comment created: ${response.html_url}`);

      return {
        type: "pr-comment",
        success: true,
        url: response.html_url,
      };
    } catch (error) {
      this.logger.error("Failed to create PR comment:", error.message);
      return {
        type: "pr-comment",
        success: false,
        error: error.message,
      };
    }
  }

  async sendWebhook(notification) {
    try {
      const webhookData = {
        type: notification.type,
        severity: notification.severity,
        subject: notification.subject,
        timestamp: notification.data.timestamp,
        branch: notification.data.branch,
        commit: notification.data.commit,
        process: notification.data.process,
        framework: notification.data.framework,
        details: notification.failure,
      };

      // This would be implemented with actual HTTP request
      // For now, just log the webhook data
      this.logger.info("📡 Webhook data prepared:", JSON.stringify(webhookData, null, 2));

      return {
        type: "webhook",
        success: true,
        data: webhookData,
      };
    } catch (error) {
      this.logger.error("Failed to send webhook:", error.message);
      return {
        type: "webhook",
        success: false,
        error: error.message,
      };
    }
  }

  async makeGitHubRequest(method, endpoint, data) {
    // This would be implemented with actual HTTP request library
    // For now, simulate the response
    const simulatedResponse = {
      html_url: `https://github.com/${this.config.github.owner}/${this.config.github.repo}/issues/123`,
      number: 123,
    };

    this.logger.debug(`GitHub API ${method} ${endpoint}:`, JSON.stringify(data, null, 2));

    return simulatedResponse;
  }

  getIssueLabels(notification) {
    const labels = ["ci-failure"];

    // Add severity label
    labels.push(`severity-${notification.severity}`);

    // Add type label
    labels.push(`type-${notification.type.replace("-", "_")}`);

    // Add framework label
    if (notification.data.framework) {
      labels.push(`framework-${notification.data.framework}`);
    }

    return labels;
  }

  async cleanupOldNotifications() {
    this.logger.info("🧹 Cleaning up old notifications");

    // This would clean up old GitHub issues, close resolved issues, etc.
    // Implementation depends on specific requirements

    try {
      // Close resolved issues
      await this.closeResolvedIssues();

      // Archive old failure history
      await this.archiveOldFailureHistory();

      this.logger.info("✅ Notification cleanup completed");
    } catch (error) {
      this.logger.error("Failed to cleanup old notifications:", error.message);
    }
  }

  async closeResolvedIssues() {
    // Implementation would check for issues that are no longer failing
    // and close them automatically
    this.logger.debug("Checking for resolved issues to close");
  }

  async archiveOldFailureHistory() {
    // Implementation would archive old failure history data
    this.logger.debug("Archiving old failure history");
  }
}

// CLI Interface
if (require.main === module) {
  const args = process.argv.slice(2);
  const options = {};

  // Parse command line arguments
  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case "--no-github":
        options.githubEnabled = false;
        break;
      case "--no-issues":
        options.createIssues = false;
        break;
      case "--no-pr-comments":
        options.commentOnPR = false;
        break;
      case "--webhook":
        options.sendWebhooks = true;
        break;
      case "--results":
        options.testResultsFile = args[++i];
        break;
      case "--help":
        console.log(`
Usage: node notification-system.js [options]

Options:
  --no-github           Disable GitHub notifications
  --no-issues          Disable GitHub issue creation
  --no-pr-comments     Disable PR comments
  --webhook            Enable webhook notifications
  --results <file>     Path to test results file
  --help              Show this help message

Environment Variables:
  GITHUB_TOKEN         GitHub API token
  GITHUB_REPOSITORY    Repository name (owner/repo)
  WEBHOOK_URL          Webhook URL for notifications

Examples:
  node notification-system.js --results testing/reports/latest.json
  node notification-system.js --no-github --webhook
                `);
        process.exit(0);
        break;
    }
  }

  const notificationSystem = new NotificationSystem(options);

  // Load test results
  let testResults = {};
  if (options.testResultsFile && fs.existsSync(options.testResultsFile)) {
    try {
      testResults = JSON.parse(fs.readFileSync(options.testResultsFile, "utf8"));
    } catch (error) {
      console.error("Failed to load test results:", error.message);
      process.exit(1);
    }
  } else {
    // Try to load from default locations
    const defaultPaths = ["testing/reports/aggregated/latest.json", "testing/reports/latest.json"];

    for (const defaultPath of defaultPaths) {
      if (fs.existsSync(defaultPath)) {
        try {
          testResults = JSON.parse(fs.readFileSync(defaultPath, "utf8"));
          break;
        } catch (error) {
          // Continue to next file
        }
      }
    }
  }

  notificationSystem
    .processTestResults(testResults)
    .then(notifications => {
      console.log(`✅ Notification processing completed: ${notifications.length} notifications sent`);
      process.exit(0);
    })
    .catch(error => {
      console.error("❌ Notification processing failed:", error.message);
      process.exit(1);
    });
}

module.exports = NotificationSystem;
